name: universal_web
version: 1.1.1+1
description: Wrapper around package:web that adds compatibility for non-web environments.
repository: https://github.com/schultek/universal_web

environment:
  sdk: ^3.4.0

dependencies:
  web: 1.1.1

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  path: ^1.8.3
  test: ^1.24.4
